apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-cluster-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-autoscaler-system
  project: default
  sources:
  - repoURL: https://github.com/dbeltman/custom-cluster-autoscaler.git
    targetRevision: master
    path: deploy/rbac   
  - chart: app-template
    helm:
      valuesObject:  
        persistence:
          config:
            enabled: true
            type: configMap
            name: node-inventory    
            globalMounts:
              - path: /config/inventory
        serviceAccount:
          create: true
          name: "custom-cluster-autoscaler"        
        defaultPodOptions:
          automountServiceAccountToken: true           
        controllers:
          main:
            containers:
              main:     
                securityContext: 
                  capabilities:
                    drop:
                      - all
                    # add: ['NET_BIND_SERVICE']
                  allowPrivilegeEscalation: false                   
                resources:
                  requests:
                    memory: "30Mi"
                    cpu: "5m"        
                image:
                  repository: ghcr.io/dbeltman/custom-cluster-autoscaler
                  pullPolicy: Always
                  tag: "master"
                env:
                - name: PRODUCTION
                  value: "True"
                envFrom:
                - secretRef:
                    name: custom-autoscaler-secret

        service:
          main:
            controller: main
            ports:
              http:
                port: 80
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true