apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-autoscaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-autoscaler-role
subjects:
- kind: ServiceAccount
  name: custom-cluster-autoscaler
  namespace:  custom-autoscaler-system